export const testData = {
  validGmail: 'durgaraoburle62@gmail.com',
  validServerEmail: 'durgarao.burle@yopmail.com',
  unregisteredEmail: 'durgarao.burle0087@yopmail.com',
  emptyEmail: '',
  withoutAt_01: 'testusergmail.com',
  withoutAt_02: 'user.domainyopmail.com',
  withoutDotInDomain_01: 'testuser@gmailcom',
  withoutDotInDomain_02: 'user@domaincom',
  withSpaces_01: 'test user@gmail.com',
  withSpaces_02: 'user@domain .com',
  withSpaces_03: ' user@gmail.com',
  withSpaces_04: 'user@domain.com ',
  specialCharBeforeAt_01:'#user@gmail.com',
  specialCharBeforeAt_02:'user!name@gmail.com',
  specialCharBeforeAt_03:'%user@gmail.com',
  specialCharAfterAt_01:'user@domain#.com',
  specialCharAfterAt_02:'user@domain!.com',
  specialCharAfterAt_03:'user@domain_.com',
  emailMinRangeMinus1: 'a@b.c',
  emailMaxRangePlus1: 'veryveryverylongemailaddress1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz@domainexampletoolong.commmmm',
  emailWithMultipleAt_01: 'user@@gmail.com',
  emailWithMultipleAt_02: 'user@domain@com',
  emailWithConsecutiveDots_01: 'user..name@gmail.com',
  emailWithConsecutiveDots_02: 'user@domain..com',
  emailWithDotPositionIssues_01: '.user@gmail.com',
  emailWithDotPositionIssues_02: 'user.@gmail.com',
  emailWithInvalidDomain_01: 'user@domain',
  emailWithInvalidDomain_02: 'user@domain.',
  emailWithInvalidDomain_03: 'user@.com'
};

export const messages = {
  invalidData: 'Please enter a valid email address',
  withoutEmailValue: 'Please enter email or phone number',
  invalidEmailWithoutAt: 'Email must contain \'@\' symbol.',
  invalidEmailWithoutDot: 'Domain must contain a \'.\'',
  invalidEmailWithSpaces: 'Email should not contain spaces',
  invalidEmailwithInvalidChars: 'Email contains invalid characters',
  invalidEmailMinRangeMinus1: 'Email is too short',
  invalidEmailMaxRangePlus1: 'Email exceeds maximum length (254 characters)',
  invalidEmailWithMultipleAt: 'Email should contain only one \'@\' symbol',
  invalidEmailWithConsecutiveDots: 'Email should not contain consecutive dots',
  invalidEmailWithDotPosition: 'Dot (.) cannot be at the start or end of local part',
  invalidEmailwithInvalidEmailDomain: 'Enter a valid email domain.',
  invalidEmailwithUnregistered: 'Email address not registered.',
  receivedOtp: 'OTP sent successfully',
  otpValidationWithoutEnterOtpAndIncompleteOtp: 'Enter 4-digit OTP',
  invalidOtpValidation: 'Invalid OTP. Please try again.',
  otpEnteredafterExpired: 'Your OTP has expired. Please click on Resend OTP.',
  checkResendText: 'Resend OTP in',
  containLoginUrl: 'https://beta.ideazmeet.com/login',
  containSignupUrl: 'https://testbot.ideazmeet.com/signup'
};